apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-user:  ## <you-mysql-user>       
  mysql-password:  ## <your-mysql-password> 
  mysql-database:  ## <your-mysql-database>    
