apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-user: <your_mysql_user>          
  mysql-password: <your_mysql_password>  
  mysql-database: <your_mysql_database>      
